# Generated by Django 6.0.1 on 2026-01-08 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizechart',
            name='main_category',
        ),
    ]
