# Generated by Django 6.0.1 on 2026-01-08 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_sizechart_main_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color_code', models.CharField(help_text='Hex color code (e.g., #FF0000)', max_length=7)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='sizechart',
            name='main_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_charts', to='products.maincategory'),
        ),
        migrations.CreateModel(
            name='DefaultSize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('size_code', models.CharField(help_text='Size code (e.g., S, M, L, XL, 32, 34, One Size)', max_length=20)),
                ('size_label', models.CharField(help_text='Display label (e.g., Small, Medium, Large)', max_length=100)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(help_text='Category this size applies to (e.g., Shirts, Sarees)', on_delete=django.db.models.deletion.CASCADE, related_name='default_sizes', to='products.category')),
            ],
            options={
                'ordering': ['category', 'display_order', 'size_code'],
                'unique_together': {('category', 'size_code')},
            },
        ),
    ]
