# Generated by Django 6.0.1 on 2026-01-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_defaultcolor_sizechart_main_category_defaultsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(),
        ),
    ]
